<a href="https://colab.research.google.com/github/rohitboltfree/Pyhon01/blob/main/Numpy_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

PRACTICE OF CONDITIONAL ARRAY

In [ ]:
'''
if(num % 2 == 0):
  print(num*2)
else:
  print(num-4)

This code is equivalent to the below code
'''
import numpy as np
num = np.arange(12)
condition_arr = np.where(num % 2 == 0, num*2, num-4)
print(condition_arr)

[ 0 -3  4 -1  8  1 12  3 16  5 20  7]


In [ ]:
import numpy as np
# random num for 2d array
# this method consist the (start,end, size(2,3))
arr = np.random.randint(2,5, size=(3,1))
print(arr)

[[2]
 [3]
 [2]]


In [ ]:
# random num for 3d array
arr1 = np.random.randint(2,5, size=(2,3,4))
print(arr1)

[[[3 4 4 2]
  [2 4 4 4]
  [4 2 2 2]]

 [[2 3 2 3]
  [3 4 3 3]
  [4 4 2 3]]]


EX1 Q1


In [ ]:
zeroes = np.zeros((4,5))
print(zeroes)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Q2

In [ ]:
ones = np.ones((3,6))
print(ones)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


Q3

In [ ]:
# array filled with random float values of dim[2,10]
random_arr = np.random.rand(2,10)
print(random_arr)

[[0.72055062 0.8280034  0.17138006 0.42440444 0.37956983 0.34840037
  0.60731865 0.24935619 0.12799156 0.08220095]
 [0.02208747 0.15479518 0.84931519 0.46658684 0.56904753 0.53412862
  0.02956837 0.49698726 0.53526837 0.04527002]]


Q4

In [ ]:
# array filled with random integer values of dim[6,3]
rand_arr1 = np.random.randint(2,10, size=(6,3))
print(rand_arr1)

[[9 8 7]
 [6 3 7]
 [9 7 2]
 [8 5 6]
 [4 5 2]
 [3 3 4]]


In [ ]:
'''
Generate a random float values of a gaussian pdf for the dimension (4,5)
'''
rand_arr2 = np.random.randn(4,5)
print(rand_arr2)


[[-0.76378711 -0.03348116  1.22835     1.56257586 -1.02951176]
 [-0.62681433  0.62670826 -0.37359159 -0.90049616 -0.04025482]
 [ 0.28510792  1.1550459  -0.3465048  -0.65421543 -0.29675541]
 [ 0.9167914   1.02266468 -0.24700142 -1.18903244  0.55545929]]


In [ ]:
'''Generate random integers in the range of 2 and 22 (inclusive)
   for the dimension (4,5) '''

rand_arr3 = np.random.randint(2,23, size=(4,5))
print(rand_arr3)

[[17 11  9  7 16]
 [ 5 21 15  6 22]
 [ 8 12 22 20  7]
 [16 17  6  2 22]]


In [ ]:
'''Generate random floating values randn() for the range between
   20 to 200 of 1D array (size = 20 ) '''

# wrong answer
# rand_arr4 = np.random.randint(20,200, size=(20))
# print(rand_arr4)

# # wrong answer 2
# rand_arr4 = np.random.randn(20) * 100 + 20
# print(rand_arr4)

# my answer
rand_arr4 = np.random.rand(20)
random_num = np.random.randint(10,100, size=(20))
arr5 = np.where(rand_arr4>20, rand_arr4<200, rand_arr4) * 100 + random_num
print(arr5)
print(rand_arr4)

# sir answer
rand_arr5 = 20 + (200-20)*np.random.rand(20)
print(rand_arr5)

[ 50.9768805  164.64551958  26.31548859 112.55302204  80.24303554
  92.98901057  38.99850097 129.19064946 111.47147361 144.13298371
  91.99345276 130.84569081 123.73710193 109.50725199  61.52623721
  96.20281092 149.84665543 106.16796163  84.18362926  52.67859034]
[0.06976881 0.6864552  0.14315489 0.59553022 0.11243036 0.02989011
 0.07998501 0.87190649 0.25471474 0.69132984 0.53993453 0.93845691
 0.34737102 0.55507252 0.33526237 0.14202811 0.62846655 0.26167962
 0.50183629 0.1467859 ]
[ 20.3311505   79.00071222 112.0937989   98.75162679  40.6958389
 155.09258608  96.81612116  37.85191589 194.17675639 120.31441858
 115.73943199  87.86493164  48.12725449  26.97265077  60.04137601
  21.20555823 183.02759044  81.3917814  138.3766025   90.81206786]


matrices addition

In [ ]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]


In [ ]:
# Problem Statement
'''1> create a 2d array
   2> add the scalar value 10 to each element of arr (using broadcasting)
   3> add the array [10,20,30] to arr (using broadcastiing) '''

Qarr = np.array([[2,3,4],[5,6,7]])
print( "real array \n",Qarr)
print("addition of 10 \n",10 + Qarr)
arr = np.array([10,20,30])
print("addition of another array ",arr + Qarr)

real array 
 [[2 3 4]
 [5 6 7]]
addition of 10 
 [[12 13 14]
 [15 16 17]]
addition of another array  [[12 23 34]
 [15 26 37]]


In [3]:
# upcating
import numpy as np
list1 = [1,2,3,4]
data = np.array(list1)
print((data.dtype))


int64


In [6]:
data2 = [2,8.9]
data1 = np.array(data2)
print((data1.dtype))

float64


In [9]:
r = np.array(['hello','world'], dtype='U5')
# array(['hello','world'], dtype='U5')
print(r.dtype)

<U5


In [11]:
data = np.array(range(1000000))
print(data)
print()
print(len(data))
print(data.size)

[     0      1      2 ... 999997 999998 999999]

1000000
1000000


In [12]:
check = np.array([[1,4,5],[2,3,4]])
print(check.size)
print(len(check))

6
2


In [22]:
a = np.random.normal(0,1,1000)
b  =np.arange(1000, dtype = np.uint8)
c = np.arange(1000, dtype = np.float64)
c += a + b
print(c)

[-1.05368897e+00  6.56685284e-01  6.82126202e+00  4.05694724e+00
  8.96537945e+00  1.00938863e+01  1.27396885e+01  1.27757041e+01
  1.68096011e+01  1.77763629e+01  1.80521278e+01  2.13311673e+01
  2.28438566e+01  2.46046081e+01  2.82637717e+01  3.14155156e+01
  3.27544288e+01  3.53400718e+01  3.47417925e+01  3.86856628e+01
  4.09829290e+01  4.13701940e+01  4.23624387e+01  4.60958101e+01
  4.65409970e+01  4.88825051e+01  5.24531163e+01  5.43705003e+01
  5.57810408e+01  5.64140131e+01  5.89870106e+01  6.20685881e+01
  6.51975959e+01  6.71425231e+01  6.81334447e+01  7.02962220e+01
  7.11174763e+01  7.32264963e+01  7.70569761e+01  7.78715881e+01
  8.07485922e+01  8.27035282e+01  8.34064771e+01  8.57401237e+01
  8.80033664e+01  8.94356558e+01  9.31223713e+01  9.35556789e+01
  9.55687236e+01  9.71931948e+01  9.97492397e+01  1.01856507e+02
  1.04649834e+02  1.06620473e+02  1.10433116e+02  1.11029156e+02
  1.11012451e+02  1.12772509e+02  1.14219072e+02  1.18446774e+02
  1.20148603e+02  1.23644